Test Build for pull request
deremenko/Expense-accounting pull request #1
Opened 2024-01-23 08:59 UTC by deremenko

2024-01-24 11:51 UTC, baklanovairina requested changes

2024-01-24 11:51 UTC, baklanovairina commented on src/App.js
> +import CostGridLayout from './components/CostGridLayout';
ужасное название, почему в нем вообще фигурирует Grid и Layout
я вот потом возьму и перепишу стили, а название останется
и что тогда потом название менять и проверять лишний раз импорты?

2024-01-24 11:51 UTC, baklanovairina commented on src/components/Button/index.jsx
> +function Button(props) {
стрелочные

2024-01-24 11:51 UTC, baklanovairina commented on src/components/Button/index.jsx
> +function Button(props) {
пропсы деструктуризируй

2024-01-24 11:51 UTC, baklanovairina commented on src/components/Button/index.jsx
> +      className ='button'
кавычки двойные

2024-01-24 11:51 UTC, baklanovairina commented on src/components/Button/index.jsx
> +      style={props.stylesButton}
класс делай

2024-01-24 11:51 UTC, baklanovairina commented on src/components/Button/index.jsx
> +    >
где type?

2024-01-24 11:51 UTC, baklanovairina commented on src/components/CostGridLayout/index.jsx
> +  const [spends, setSpends] = useState([...initialSpending]);
определись либо везде Cost либо spends используешь, а то компонент Cost, а в нем какие то spends

и spends пустой по умолчанию

2024-01-24 11:51 UTC, baklanovairina commented on src/components/CostGridLayout/index.jsx
> +  const [placeholders, setPlaceholders] = useState(["Куда было потрачено", "Сколько было потрачено"]);
placeholder вообще не стейт, это не изменяемое поле и не контролируемое, пропсами его передавай, стейт для него не нужен

2024-01-24 11:51 UTC, baklanovairina commented on src/components/CostGridLayout/index.jsx
> +    expenseSpend: '',
опачки, а тут какие то expense появились
все синонимы решил перебрать и запутать побольше?

2024-01-24 11:51 UTC, baklanovairina commented on src/components/CostGridLayout/index.jsx
> +  const [textError, setTextError] = useState('Пожалуйста, введите корректные данные.');
пустая ошибка по умолчанию 
и эти 2 стейта можно сделать 1 в виде объекта

2024-01-24 11:51 UTC, baklanovairina commented on src/components/CostGridLayout/index.jsx
> +  const [editSpend, setEditSpend] = useState({
редактируемый будет edited, а не edit
edit - это редактировать, а у тебя переменная, она не может что-то редактировать

2024-01-24 11:51 UTC, baklanovairina commented on src/components/CostGridLayout/index.jsx
> +  const stylesAddButton = {
что здесь стили забыли??

2024-01-24 11:51 UTC, baklanovairina commented on src/components/CostGridLayout/index.jsx
> +    return () => {};
ну а смысл в нем, если он пустой?

2024-01-24 11:51 UTC, baklanovairina commented on src/components/CostGridLayout/index.jsx
> +    addSpend()
функция ради функции

2024-01-24 11:51 UTC, baklanovairina commented on src/components/CostGridLayout/index.jsx
> +  const countTotal = () => {
calcTotalAmount

2024-01-24 11:51 UTC, baklanovairina commented on src/components/CostGridLayout/index.jsx
> +    setEditSpend((prevState) => ({
это тебе не классовые компоненты
вообще не желательно делать преобразования какие то внутри setState
лучше туда сразу записывать итоговое значение

2024-01-24 11:51 UTC, baklanovairina commented on src/components/CostGridLayout/index.jsx
> +    setEditSpend((prevState) => ({
и вообще используй find 
а не какой то непонятный второй index, не ясно зачем он нужен, когда есть idSpend

2024-01-24 11:51 UTC, baklanovairina commented on src/components/CostGridLayout/index.jsx
> +    changeSpend(index, idSpend);
снова функция ради функции и снова почему то 2 индекса

2024-01-24 11:51 UTC, baklanovairina commented on src/components/CostGridLayout/index.jsx
> +  const clickEditCancel = () => {
опять клики какие то

2024-01-24 11:51 UTC, baklanovairina commented on src/components/CostGridLayout/index.jsx
> +    console.log(editSpend.editedDate);
консоли!!

2024-01-24 11:51 UTC, baklanovairina commented on src/components/CostGridLayout/index.jsx
> +    if (!validateText || !Number(editSpend.editedExpense) || !Date(editSpend.editedDate)) {
проверяй по очереди поля и выводи индивидуальную ошибку для каждого, а не общую какую то

2024-01-24 11:51 UTC, baklanovairina commented on src/components/CostGridLayout/index.jsx
> +    spendsClone[index] = {
find!

2024-01-24 11:51 UTC, baklanovairina commented on src/components/CostGridLayout/index.jsx
> +    setSpends([...spendsClone]);
зачем копия??

2024-01-24 11:51 UTC, baklanovairina commented on src/components/CostGridLayout/index.jsx
> +    setEditSpend(prevState => ({
зачем prevState???

2024-01-24 11:51 UTC, baklanovairina commented on src/components/CostGridLayout/index.jsx
> +    setIdEditedSpend(null);
почему в добавлении расхода вообще есть какая то логика редактирования??

2024-01-24 11:51 UTC, baklanovairina commented on src/components/CostGridLayout/index.jsx
> +    const validateExpense = validateInput(inputSpend.expenseSpend);
вообще не пойму что за вторая строка и зачем она? в чем ее отличие от validateText?

2024-01-24 11:51 UTC, baklanovairina commented on src/components/CostGridLayout/index.jsx
> +    if (!validateText || !Number(inputSpend.expenseSpend)) {
читай про ошибки выше

2024-01-24 11:51 UTC, baklanovairina commented on src/components/CostGridLayout/index.jsx
> +      expense: validateExpense,
ааа, так text это место расхода. а expense - сумма
назови корректно уже свойства, а то только к концу кода что-то начинаешь понимать

2024-01-24 11:51 UTC, baklanovairina commented on src/components/CostGridLayout/index.jsx
> +    setInputSpend(prevState => ({
читай выше

2024-01-24 11:51 UTC, baklanovairina commented on src/components/CostGridLayout/index.jsx
> +    let spendsClone = spends.filter((spend) => {
что еще за клон?
и почему let?

2024-01-24 11:51 UTC, baklanovairina commented on src/components/CostGridLayout/index.jsx
> +    setSpends( [...spendsClone]);
зачем снова копия?

2024-01-24 11:51 UTC, baklanovairina commented on src/components/CostGridLayout/index.jsx
> +      <p className="costGridLayout__blockTitles">Учет моих расходов</p>
это вообще h - заголовок, а не p

2024-01-24 11:51 UTC, baklanovairina commented on src/components/CostGridLayout/index.jsx
> +        <p>Куда было потрачено</p>
это вообще label и почему он не в InputLine создан??

2024-01-24 11:51 UTC, baklanovairina commented on src/components/CostGridLayout/index.jsx
> +          keyStateObject={"textSpend"}
зачем здесь скобки
и что за название такое keyStateObject?? это name? id?

2024-01-24 11:51 UTC, baklanovairina commented on src/components/CostGridLayout/index.jsx
> +          actionButton={() => {handleAddSpendButton()}}
опять объявление

2024-01-24 11:51 UTC, baklanovairina commented on src/components/CostGridLayout/index.jsx
> +        <Total countTotal={countTotal} />
этот div зачем здесь? тогда в Total его кидай

2024-01-24 11:51 UTC, baklanovairina commented on src/components/CostGridLayout/index.jsx
> +      <div className="costGridLayout__blockListExpenses">
а этот div нельзя в SpendList кинуть?

2024-01-24 11:51 UTC, baklanovairina commented on src/components/CostGridLayout/index.jsx
> +          handleEditChange={handleEditChange}
как то дофига функций редактирования 
либо у тебя серьезные проблемы с неймингом
это clickEditConfir={clickEditConfir} что то редактирует 
handleEditSpendButton={handleEditSpendButton} - это обрабатывает редактирование
handleEditChange тут вообще напихан и Edit и Change чтобы точно было понятно, это функция редактирования/изменения

2024-01-24 11:51 UTC, baklanovairina commented on src/components/CostGridLayout/index.jsx
> +          keyEditedSpend={["editedText","editedDate","editedExpense"]}
снова какие то странные кеи, причет то это элемент, то это массив

2024-01-24 11:51 UTC, baklanovairina commented on src/components/ErrorMessage/index.jsx
> +function ErrorMessage(props) {
выше читай

2024-01-24 11:51 UTC, baklanovairina commented on src/components/InputLine/index.jsx
> +
лишняя пустая строка

2024-01-24 11:51 UTC, baklanovairina commented on src/components/InputLine/index.jsx
> +    <input className="inputLine"
переносы

2024-01-24 11:51 UTC, baklanovairina commented on src/components/InputLine/index.jsx
> +      value={props.value}
где type? name или id?

2024-01-24 11:51 UTC, baklanovairina commented on src/components/InputLine/index.jsx
> +      onChange={(event) => {props.handleInputValue(event,props.keyStateObject)}}
props.keyStateObject???
что ? name создай уже и через event его доставай потом в handleInputValue

а и handleInputValue поменяй название handleChangeInput

2024-01-24 11:51 UTC, baklanovairina commented on src/components/Spend/index.jsx
> +import trashBoxIcon from '../../svg/trash-box.svg';
порядок

2024-01-24 11:51 UTC, baklanovairina commented on src/components/Spend/index.jsx
> +            actionButton={() => props.clickEditConfir(props.index, props.id)}
одного айди достаточно и уже точно не маповский

2024-01-24 11:51 UTC, baklanovairina commented on src/components/SpendList/index.jsx
> +function SpendList(props) {
вообще лишний компонент

2024-01-24 11:51 UTC, baklanovairina commented on src/components/Spend/index.jsx
> +          <div className='spend__name'>
это вообще отдельный компонент - форма редактирования

2024-01-24 11:51 UTC, baklanovairina commented on src/components/SpendList/index.jsx
> +        <Spend
где условный рендеринг между обычным расходом и формой редактирования?

2024-01-24 11:51 UTC, baklanovairina commented on src/components/Total/index.jsx
> +    <p className="total">Итого: {props.countTotal()} </p>
ты что функцию здесь вызываешь??
т е он каждый раз при сборке будет считать??
делай переменной

2024-01-24 11:51 UTC, baklanovairina commented on src/constants.js
> +  { id: generateUniqueId(),
```
{ 
  id: generateUniqueId(),
```

2024-01-24 11:51 UTC, baklanovairina commented on src/helpers/validateInput.js
> +  return singleSpacesOnly.length > 0 ? singleSpacesOnly : false;
т е ты либо фолс возвращаешь либо строку??
итак что такое чистая функция? Подумай и перепиши эту функцию

2024-01-25 06:44 UTC, deremenko commented on src/App.js
> +import CostGridLayout from './components/CostGridLayout';
Completed

2024-01-25 09:59 UTC, deremenko commented on src/components/Button/index.jsx
> +function Button(props) {
Completed

2024-01-25 10:08 UTC, deremenko commented on src/components/Button/index.jsx
> +      className ='button'
Completed

2024-01-25 10:28 UTC, deremenko commented on src/components/Button/index.jsx
> +      style={props.stylesButton}
Completed

2024-01-25 10:29 UTC, deremenko commented on src/components/Button/index.jsx
> +    >
Completed

2024-01-25 10:29 UTC, deremenko commented on src/components/CostGridLayout/index.jsx
> +  const [spends, setSpends] = useState([...initialSpending]);
Completed

2024-01-25 10:30 UTC, deremenko commented on src/components/CostGridLayout/index.jsx
> +  const [placeholders, setPlaceholders] = useState(["Куда было потрачено", "Сколько было потрачено"]);
Completed

2024-01-25 10:33 UTC, deremenko commented on src/components/CostGridLayout/index.jsx
> +    expenseSpend: '',
Completed

2024-01-25 10:44 UTC, deremenko commented on src/components/CostGridLayout/index.jsx
> +  const [textError, setTextError] = useState('Пожалуйста, введите корректные данные.');
Completed

2024-01-25 10:46 UTC, deremenko commented on src/components/CostGridLayout/index.jsx
> +  const [editSpend, setEditSpend] = useState({
Completed

2024-01-25 10:46 UTC, deremenko commented on src/components/CostGridLayout/index.jsx
> +  const stylesAddButton = {
Completed

2024-01-25 10:46 UTC, deremenko commented on src/components/CostGridLayout/index.jsx
> +    return () => {};
Completed

2024-01-25 10:47 UTC, deremenko commented on src/components/CostGridLayout/index.jsx
> +    addSpend()
Completed

2024-01-25 10:47 UTC, deremenko commented on src/components/CostGridLayout/index.jsx
> +  const countTotal = () => {
Completed

2024-01-25 10:50 UTC, deremenko commented on src/components/CostGridLayout/index.jsx
> +  const clickEditCancel = () => {
Completed

2024-01-25 10:51 UTC, deremenko commented on src/components/CostGridLayout/index.jsx
> +    console.log(editSpend.editedDate);
Completed

2024-01-25 12:00 UTC, deremenko commented on src/constants.js
> +  { id: generateUniqueId(),
Completed

2024-01-25 12:01 UTC, deremenko commented on src/helpers/validateInput.js
> +  return singleSpacesOnly.length > 0 ? singleSpacesOnly : false;
Completed

2024-01-25 12:01 UTC, deremenko commented on src/components/Spend/index.jsx
> +            actionButton={() => props.clickEditConfir(props.index, props.id)}
Completed

2024-01-25 12:09 UTC, deremenko commented on src/components/CostGridLayout/index.jsx
> +    setEditSpend((prevState) => ({
Completed

2024-01-25 12:09 UTC, deremenko commented on src/components/CostGridLayout/index.jsx
> +    changeSpend(index, idSpend);
Completed

2024-01-25 13:59 UTC, deremenko commented on src/components/CostGridLayout/index.jsx
> +    spendsClone[index] = {
Completed

2024-01-25 14:01 UTC, deremenko commented on src/components/CostGridLayout/index.jsx
> +    setSpends([...spendsClone]);
Completed

2024-01-25 14:03 UTC, deremenko commented on src/components/CostGridLayout/index.jsx
> +    setEditSpend(prevState => ({
Completed

2024-01-25 14:05 UTC, deremenko commented on src/components/CostGridLayout/index.jsx
> +    setIdEditedSpend(null);
По данной переменной у меня идет проверка на ошибку. Так что я обнуляю ее, что бы ошибка невозникала когда пользователь резко бросат редактировать таск

2024-01-25 14:06 UTC, deremenko commented on src/components/CostGridLayout/index.jsx
> +    if (!validateText || !Number(inputSpend.expenseSpend)) {
??

2024-01-25 14:06 UTC, deremenko commented on src/components/CostGridLayout/index.jsx
> +      expense: validateExpense,
Completed

2024-01-25 14:33 UTC, deremenko commented on src/components/CostGridLayout/index.jsx
> +    setInputSpend(prevState => ({
Completed

2024-01-25 14:33 UTC, deremenko commented on src/components/CostGridLayout/index.jsx
> +    let spendsClone = spends.filter((spend) => {
Completed

2024-01-25 14:33 UTC, deremenko commented on src/components/CostGridLayout/index.jsx
> +    setSpends( [...spendsClone]);
Completed

2024-01-25 14:38 UTC, deremenko commented on src/components/CostGridLayout/index.jsx
> +      <p className="costGridLayout__blockTitles">Учет моих расходов</p>
Completed

2024-01-25 14:47 UTC, deremenko commented on src/components/CostGridLayout/index.jsx
> +        <p>Куда было потрачено</p>
Completed

2024-01-25 14:47 UTC, deremenko commented on src/components/CostGridLayout/index.jsx
> +          keyStateObject={"textSpend"}
Completed

2024-01-25 14:49 UTC, deremenko commented on src/components/CostGridLayout/index.jsx
> +          actionButton={() => {handleAddSpendButton()}}
Completed

2024-01-25 14:51 UTC, deremenko commented on src/components/CostGridLayout/index.jsx
> +        <Total countTotal={countTotal} />
Это один из фрагменов сетки

2024-01-25 14:51 UTC, deremenko commented on src/components/CostGridLayout/index.jsx
> +          handleEditChange={handleEditChange}
Completed

2024-01-25 14:54 UTC, deremenko commented on src/components/CostGridLayout/index.jsx
> +          keyEditedSpend={["editedText","editedDate","editedExpense"]}
Completed

2024-01-25 14:54 UTC, deremenko commented on src/components/ErrorMessage/index.jsx
> +function ErrorMessage(props) {
Completed

2024-01-25 14:54 UTC, deremenko commented on src/components/InputLine/index.jsx
> +
Completed

2024-01-25 14:54 UTC, deremenko commented on src/components/Total/index.jsx
> +    <p className="total">Итого: {props.countTotal()} </p>
Completed

2024-01-25 14:55 UTC, deremenko commented on src/components/Spend/index.jsx
> +          <div className='spend__name'>
Completed

2024-01-25 14:55 UTC, deremenko commented on src/components/SpendList/index.jsx
> +        <Spend
Completed

2024-01-26 11:25 UTC, baklanovairina requested changes

2024-01-26 11:25 UTC, baklanovairina commented on src/components/Button/index.jsx
> +const buttonClass = isButtonStyle ? 'addStyle' : 'spendStyle';
а если я захочу третий вообще другой класс передать, кнопка та катомная и переиспользуемая, а ты сделал ее зависимой от двух 
функционалов и стиле
в общем ты должен не булево isButtonStyle передавать, а класс дополнительный
А по умолчанию укажи его пустой строкой

2024-01-26 11:25 UTC, baklanovairina commented on src/components/Button/index.jsx
> +      type='button'
кавычки двойные

2024-01-26 11:25 UTC, baklanovairina commented on src/components/Button/styles.css
> +.button_spendStyle {
отступы между классами

2024-01-26 11:25 UTC, baklanovairina commented on src/components/EditInput/index.jsx
> +          nameFieldObject={"text"}
опять эти скобки
что ты их везде пишешь, какой в них смысл для передачи строки??

2024-01-26 11:25 UTC, baklanovairina commented on src/components/EditInput/index.jsx
> +        actionButton={() => changeSpend(id)}
type??

2024-01-26 11:25 UTC, baklanovairina commented on src/components/InputLine/index.jsx
> +    <>
не плоди фрагменты, ты ухудшаешь этим верстку
здесь явно нужен блок - div

2024-01-26 11:25 UTC, baklanovairina commented on src/components/InputLine/index.jsx
> +        onChange={(event) => handleInputValue(event, nameFieldObject)}
просто name
а вообще ты можешь создать его в инпуте, это его атрибут такой
и потом передавать только event и из него доставать event.target.name

2024-01-26 11:25 UTC, baklanovairina commented on src/components/Spend/index.jsx
> +        <div className='spend__errorBlock'>
таб пропустил
+кавычки

2024-01-26 11:25 UTC, baklanovairina commented on src/components/Spend/index.jsx
> +      ) : (
почему ты делаешь условный рендеринг внутри Spend?
делай его в процессе мапа в компоненте выше

2024-01-26 11:25 UTC, baklanovairina commented on src/components/Spend/index.jsx
> +            actionButton={() => handleEditedSpendButton(spend.id,)}
запятая лишняя

2024-01-26 11:25 UTC, baklanovairina commented on src/components/SpendsTracker/index.jsx
> +import React, { useState, useEffect } from 'react';
зачем React импортируешь? Он автоматически импортируется

2024-01-26 11:25 UTC, baklanovairina commented on src/components/SpendsTracker/index.jsx
> +  }, [spends.length]);
только когда длина? 
а если проведем редактирование? Длина массива останется прежней, но сумма расхода может изменится

2024-01-26 11:25 UTC, baklanovairina commented on src/components/SpendsTracker/index.jsx
> +    const indexSpend = spends.findIndex(item => item.id === idSpend);
индекс какого расхода? - редактируемого

2024-01-26 11:25 UTC, baklanovairina commented on src/components/SpendsTracker/index.jsx
> +    let spendsBuffer = spends.filter((spend) => {
const

2024-01-26 11:25 UTC, baklanovairina commented on src/components/SpendsTracker/index.jsx
> +          inputheader={"Куда было потрачено"}
опять скобки

2024-01-26 11:25 UTC, baklanovairina commented on src/components/SpendsTracker/index.jsx
> +      {spends.map((spend, index) => (
таб

2024-01-26 11:59 UTC, deremenko commented on src/components/Button/index.jsx
> +const buttonClass = isButtonStyle ? 'addStyle' : 'spendStyle';
Completed

2024-01-26 12:01 UTC, deremenko commented on src/components/Button/index.jsx
> +      type='button'
Completed

2024-01-26 12:01 UTC, deremenko commented on src/components/Button/styles.css
> +.button_spendStyle {
Completed

2024-01-26 12:02 UTC, deremenko commented on src/components/EditInput/index.jsx
> +          nameFieldObject={"text"}
Completed

2024-01-26 12:05 UTC, deremenko commented on src/components/EditInput/index.jsx
> +        actionButton={() => changeSpend(id)}
Completed

2024-01-26 12:11 UTC, deremenko commented on src/components/InputLine/index.jsx
> +    <>
Completed

2024-01-26 12:15 UTC, deremenko commented on src/components/InputLine/index.jsx
> +        onChange={(event) => handleInputValue(event, nameFieldObject)}
Completed

2024-01-26 12:17 UTC, deremenko commented on src/components/Spend/index.jsx
> +        <div className='spend__errorBlock'>
Completed

2024-01-26 12:18 UTC, deremenko commented on src/components/Spend/index.jsx
> +            actionButton={() => handleEditedSpendButton(spend.id,)}
Completed

2024-01-26 12:19 UTC, deremenko commented on src/components/SpendsTracker/index.jsx
> +import React, { useState, useEffect } from 'react';
Completed

2024-01-26 12:57 UTC, deremenko commented on src/components/Spend/index.jsx
> +      ) : (
Completed

2024-01-26 12:59 UTC, deremenko commented on src/components/SpendsTracker/index.jsx
> +  }, [spends.length]);
Completed

2024-01-26 13:00 UTC, deremenko commented on src/components/SpendsTracker/index.jsx
> +    const indexSpend = spends.findIndex(item => item.id === idSpend);
Completed

2024-01-26 13:01 UTC, deremenko commented on src/components/SpendsTracker/index.jsx
> +          inputheader={"Куда было потрачено"}
Completed

2024-01-26 13:01 UTC, deremenko commented on src/components/SpendsTracker/index.jsx
> +    let spendsBuffer = spends.filter((spend) => {
Completed

2024-01-26 13:01 UTC, deremenko commented on src/components/SpendsTracker/index.jsx
> +      {spends.map((spend, index) => (
Completed

2024-01-29 08:24 UTC, baklanovairina commented on src/components/InputLine/index.jsx
> +      <label>{inputheader}</label>
добавь htmlFor
он нужен для привязки инпута и лейбла между собой

2024-01-29 08:24 UTC, baklanovairina commented on src/components/InputLine/index.jsx
> +        onChange={(event) => handleInputValue(event, event.target.name)}
да не надо отдельно передавать event.target.name
ты же event передаешь, потом в следующей функции достанешь name, а то по сути ты дважды передаешь  event.target.name: отдельно и в объекте event

2024-01-29 08:24 UTC, baklanovairina commented on src/components/Spend/index.jsx
> +        <p className="spend__name">{index + 1}){spend.text}</p>
табы 2 пробела

2024-01-29 08:24 UTC, baklanovairina commented on src/components/SpendsTracker/index.jsx
> +        console.log(spend["amount"]);
консоль!

2024-01-29 09:15 UTC, deremenko commented on src/components/InputLine/index.jsx
> +      <label>{inputheader}</label>
Completed

2024-01-29 09:16 UTC, deremenko commented on src/components/InputLine/index.jsx
> +        onChange={(event) => handleInputValue(event, event.target.name)}
Completed

2024-01-29 09:16 UTC, deremenko commented on src/components/Spend/index.jsx
> +        <p className="spend__name">{index + 1}){spend.text}</p>
Completed

2024-01-29 09:17 UTC, deremenko commented on src/components/SpendsTracker/index.jsx
> +        console.log(spend["amount"]);
Completed

2024-01-29 13:39 UTC, merged